'use client'

import { FormEvent, useState } from 'react'
import { ArrowDownRight, ArrowRight, Check, ChevronRight, Clock3, HeartHandshake, Laptop, Leaf, Mail, Menu, MessageCircleHeart, ShieldCheck, Sparkles, Star, Users, X } from 'lucide-react'

const navLinks = [['Servicios', '#servicios'], ['Sobre mí', '#nosotros'], ['Proceso', '#proceso'], ['Tarifas', '#tarifas'], ['Contacto', '#contacto']]
const services = [
  { icon: Leaf, title: 'Terapia individual', text: 'Un espacio confidencial para trabajar ansiedad, depresión, duelo y crecimiento personal.', tag: 'Para ti' },
  { icon: HeartHandshake, title: 'Terapia de pareja', text: 'Herramientas para comunicarse con claridad, resolver conflictos y recuperar la conexión.', tag: 'Para dos' },
  { icon: Users, title: 'Terapia familiar', text: 'Acompañamiento para comprender dinámicas, establecer acuerdos y fortalecer los vínculos.', tag: 'En familia' },
  { icon: Laptop, title: 'Sesiones online', text: 'Atención cercana desde donde estés, con la misma calidad, privacidad y continuidad.', tag: 'A distancia' },
]
const processSteps = [
  ['Primera consulta gratuita', 'Nos conocemos, escucho tu situación y resolvemos tus dudas.'],
  ['Evaluación inicial', 'Comprendemos lo que estás viviendo y aquello que necesitas.'],
  ['Plan terapéutico', 'Definimos objetivos claros y una frecuencia que funcione para ti.'],
  ['Sesiones y seguimiento', 'Avanzamos a tu ritmo y ajustamos el proceso según tu progreso.'],
]
const prices = [
  { title: 'Sesión individual', price: '$900', time: '50 minutos', points: ['Evaluación personalizada', 'Confidencialidad total', 'Presencial u online'] },
  { title: 'Terapia de pareja', price: '$1,100', time: '60 minutos', points: ['Sesiones conjuntas', 'Acuerdos y comunicación', 'Plan para ambos'], popular: true },
  { title: 'Sesión online', price: '$800', time: '50 minutos', points: ['Desde cualquier lugar', 'Enlace privado', 'Horarios flexibles'] },
]
type FormState = { nombre: string; email: string; telefono: string; terapia: string; modalidad: string; horario: string; fecha: string; hora: string; motivo: string; primeraVez: string }
const initialForm: FormState = { nombre: '', email: '', telefono: '', terapia: '', modalidad: '', horario: '', fecha: '', hora: '', motivo: '', primeraVez: '' }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [form, setForm] = useState<FormState>(initialForm)
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')
  const update = (field: keyof FormState, value: string) => setForm((current) => ({ ...current, [field]: value }))

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus('loading')
    try {
      const base = process.env.NEXT_PUBLIC_CONSTRUCTOR_API
      const project = process.env.NEXT_PUBLIC_PROJECT_ID
      if (!base || !project) throw new Error('Configuración no disponible')
      const response = await fetch(`${base}/v1/forms/${project}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) })
      if (!response.ok) throw new Error('No se pudo enviar')
      setStatus('success')
    } catch { setStatus('error') }
  }

  return <main className="overflow-hidden bg-ivory text-charcoal">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-charcoal/8 bg-ivory/90 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
        <a href="#inicio" aria-label="Mente Plena, ir al inicio" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-sage text-white"><Leaf size={19}/></span><span className="font-serif text-xl font-semibold tracking-tight">Mente Plena</span></a>
        <div className="hidden items-center gap-7 lg:flex">{navLinks.map(([label, href]) => <a key={href} href={href} className="text-sm text-muted transition hover:text-clay">{label}</a>)}<a href="#contacto" className="rounded-full bg-clay px-5 py-3 text-sm font-semibold text-white transition hover:bg-clay-dark">Agendar sesión</a></div>
        <button type="button" onClick={() => setMenuOpen(!menuOpen)} className="grid size-11 place-items-center rounded-full border border-charcoal/10 lg:hidden" aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menuOpen}>{menuOpen ? <X size={21}/> : <Menu size={21}/>}</button>
      </div>
      <div className={`absolute inset-x-0 top-20 border-b border-charcoal/8 bg-ivory px-5 py-5 shadow-xl transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] lg:hidden ${menuOpen ? 'pointer-events-auto translate-y-0 opacity-100' : 'pointer-events-none -translate-y-4 opacity-0'}`}>
        {navLinks.map(([label, href], index) => <a key={href} href={href} onClick={() => setMenuOpen(false)} style={{transitionDelay: menuOpen ? `${index * 60}ms` : '0ms'}} className={`flex items-center justify-between border-b border-charcoal/8 py-4 transition-all duration-500 ${menuOpen ? 'translate-x-0 opacity-100' : '-translate-x-3 opacity-0'}`}>{label}<ChevronRight size={17}/></a>)}
      </div>
    </nav>

    <section id="inicio" className="relative min-h-[760px] bg-gradient-to-br from-ivory via-ivory to-sage-light pt-20">
      <div className="mx-auto grid min-h-[680px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8">
        <div className="relative z-10 max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-sage/25 bg-white/70 px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-sage-dark"><ShieldCheck size={15}/> Psicología clínica en CDMX y online</div>
          <h1 className="font-serif text-5xl leading-[1.06] font-medium tracking-[-.035em] sm:text-6xl lg:text-7xl">Un espacio seguro para <em className="font-normal text-clay">sanar</em> y crecer</h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-muted">Terapia psicológica individual, de pareja y familiar. Un acompañamiento profesional, cálido y confidencial para volver a sentirte en equilibrio.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#contacto" className="group inline-flex items-center justify-center gap-3 rounded-full bg-clay px-6 py-4 font-semibold text-white transition hover:bg-clay-dark">Agendar primera sesión <ArrowRight className="transition group-hover:translate-x-1" size={18}/></a><a href="#nosotros" className="inline-flex items-center justify-center rounded-full border border-clay px-6 py-4 font-semibold text-clay transition hover:bg-clay hover:text-white">Conocer más</a></div>
          <p className="mt-6 flex items-center gap-2 text-sm text-muted"><Clock3 size={16} className="text-sage"/> Respuesta a solicitudes en un plazo de 24 horas</p>
        </div>
        <div className="relative mx-auto aspect-square w-full max-w-[530px]" aria-label="Composición abstracta que representa calma y crecimiento"><div className="absolute inset-[8%] rounded-[48%_52%_42%_58%] bg-sage/70 shadow-[0_35px_90px_rgba(81,109,83,.22)]"/><div className="absolute right-[4%] top-[4%] size-[48%] rounded-full bg-clay/80 mix-blend-multiply"/><div className="absolute bottom-[3%] left-[2%] size-[56%] rounded-full bg-[#e8d8c8]"/><div className="absolute inset-[24%] grid place-items-center rounded-full border border-white/60 bg-ivory/85 text-center shadow-xl backdrop-blur-sm"><div><Sparkles className="mx-auto mb-4 text-clay" size={28}/><p className="font-serif text-2xl">Tu proceso,<br/>a tu ritmo.</p></div></div></div>
      </div>
    </section>

    <section aria-label="Indicadores de confianza" className="bg-charcoal text-white"><div className="mx-auto grid max-w-7xl grid-cols-2 px-5 py-8 lg:grid-cols-4 lg:px-8">{[['1,200+', 'pacientes atendidas'], ['11 años', 'de experiencia clínica'], ['10045829', 'cédula profesional'], ['Online', 'y presencial en CDMX']].map(([value,label],i) => <div key={label} className={`px-3 py-4 lg:px-8 ${i > 0 ? 'border-l border-white/12' : ''}`}><span className="mb-3 block h-0.5 w-8 bg-clay"/><strong className="font-serif text-2xl font-medium sm:text-3xl">{value}</strong><p className="mt-1 text-xs text-white/60 sm:text-sm">{label}</p></div>)}</div></section>

    <section id="servicios" className="scroll-mt-20 bg-ivory py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr] lg:gap-16">
      <div><p className="eyebrow">Cómo puedo acompañarte</p><h2 className="section-title mt-4">La terapia que se adapta a tu momento</h2><p className="mt-6 leading-7 text-muted">No tienes que tener todas las respuestas antes de empezar. Juntos encontraremos la forma de acompañarte.</p></div>
      <div className="grid gap-4 sm:grid-cols-2">{services.map((service,i) => <article key={service.title} className={`group rounded-[2rem] border border-charcoal/8 p-7 transition duration-300 hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(45,45,45,.08)] ${i===1 ? 'bg-sage-light':'bg-white'}`}><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-sage/12 text-sage-dark"><service.icon size={24}/></span><span className="text-xs uppercase tracking-[.15em] text-muted">{service.tag}</span></div><h3 className="mt-8 font-serif text-2xl">{service.title}</h3><p className="mt-3 min-h-20 leading-7 text-muted">{service.text}</p><a href="#contacto" className="mt-5 inline-flex items-center gap-2 font-semibold text-clay">Agendar <ArrowDownRight size={17}/></a></article>)}</div>
    </div></div></section>

    <section id="nosotros" className="scroll-mt-20 bg-sage-light py-24 sm:py-32"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 lg:grid-cols-[.85fr_1.15fr] lg:px-8">
      <div className="relative mx-auto w-full max-w-md pb-10 pr-8"><div className="aspect-[4/5] overflow-hidden rounded-[12rem_12rem_2rem_2rem] bg-gradient-to-b from-[#d6c3ac] to-sage"><div className="flex h-full flex-col items-center justify-end"><div className="size-32 rounded-full bg-[#b87d57]"/><div className="-mt-2 h-[48%] w-[70%] rounded-t-[8rem] bg-[#faf8f5]/85"/></div></div><div className="absolute bottom-0 right-0 max-w-[210px] rounded-2xl bg-charcoal p-5 text-white shadow-xl"><p className="font-serif text-3xl">11 años</p><p className="mt-1 text-sm text-white/65">acompañando procesos de cambio</p></div></div>
      <div className="border-l-2 border-clay pl-6 sm:pl-10"><p className="eyebrow">Sobre mí</p><h2 className="section-title mt-4">Dra. Valentina Torres</h2><p className="mt-3 text-sm font-semibold uppercase tracking-[.12em] text-sage-dark">Psicóloga clínica · Cédula 10045829 · Maestría UNAM</p><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">Creo en una terapia cercana y sin juicios. Mi trabajo parte de escuchar tu historia con atención para construir un proceso claro, respetuoso y profundamente humano.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{['Trastornos de ansiedad','Depresión y duelo','Pareja y relaciones','Autoestima y desarrollo'].map(item => <div key={item} className="flex items-center gap-3 rounded-xl bg-white/70 p-4"><Check size={18} className="text-clay"/><span className="text-sm font-medium">{item}</span></div>)}</div></div>
    </div></section>

    <section id="proceso" className="scroll-mt-20 bg-charcoal py-24 text-white sm:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-xl"><p className="eyebrow text-clay">Tu camino en terapia</p><h2 className="section-title mt-4 text-white">Empezar puede sentirse más sencillo</h2></div><div className="mt-16 grid lg:grid-cols-4">{processSteps.map(([title,text],index) => <article key={title} className="relative border-l border-white/15 px-6 pb-10 lg:border-l-0 lg:border-t lg:pb-0 lg:pt-10"><span className="absolute -left-5 top-0 grid size-10 place-items-center rounded-full bg-sage font-serif text-lg lg:-top-5 lg:left-6">{index+1}</span><h3 className="font-serif text-xl lg:mt-4">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{text}</p></article>)}</div></div></section>

    <section id="tarifas" className="scroll-mt-20 bg-ivory py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="text-center"><p className="eyebrow">Tarifas transparentes</p><h2 className="section-title mx-auto mt-4 max-w-2xl">Tu bienestar es una inversión en ti</h2><p className="mt-5 text-muted">Pago por sesión, sin permanencias ni paquetes obligatorios.</p></div><div className="mt-14 grid items-center gap-5 lg:grid-cols-3">{prices.map(price => <article key={price.title} className={`relative rounded-[2rem] border p-7 sm:p-9 ${price.popular ? 'border-clay bg-white shadow-[0_24px_70px_rgba(196,135,90,.16)] lg:py-12':'border-charcoal/10 bg-white/60'}`}>{price.popular && <span className="absolute right-7 top-0 -translate-y-1/2 rounded-full bg-clay px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-white">Más elegida</span>}<h3 className="font-serif text-2xl">{price.title}</h3><div className="mt-6 flex items-end gap-2"><span className="font-serif text-5xl">{price.price}</span><span className="pb-1 text-sm text-muted">MXN</span></div><p className="mt-2 text-sm text-muted">Sesión de {price.time}</p><div className="my-7 h-px bg-charcoal/10"/><ul className="space-y-4">{price.points.map(point => <li key={point} className="flex gap-3 text-sm"><Check size={18} className="text-sage"/>{point}</li>)}</ul><a href="#contacto" className={`mt-8 flex items-center justify-center rounded-full px-5 py-3.5 font-semibold transition ${price.popular ? 'bg-clay text-white hover:bg-clay-dark':'border border-charcoal/15 hover:border-clay hover:text-clay'}`}>Agendar sesión</a></article>)}</div></div></section>

    <section className="bg-sage-light py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Palabras de pacientes</p><h2 className="section-title mt-4">Historias contadas con discreción</h2><p className="mt-5 text-sm leading-6 text-muted">Los testimonios se muestran con iniciales para proteger la identidad de cada paciente.</p></div><div className="grid gap-4 md:grid-cols-2"><blockquote className="rounded-[2rem] bg-white p-7 md:row-span-2 md:flex md:flex-col md:justify-between"><div><div className="flex gap-1 text-clay">{[1,2,3,4,5].map(n => <Star key={n} size={15} fill="currentColor"/>)}</div><p className="mt-8 font-serif text-2xl leading-relaxed">“Encontré un lugar donde pude hablar sin miedo. La terapia me dio claridad y herramientas que sigo usando cada día.”</p></div><footer className="mt-10 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-clay/15 font-bold text-clay">AM</span><span className="text-sm text-muted">Paciente de terapia individual</span></footer></blockquote>{[['“Aprendimos a escucharnos de nuevo y a conversar desde un lugar más amable.”','LC','Terapia de pareja'],['“Las sesiones online me permitieron cuidar mi proceso incluso durante un cambio de ciudad.”','RG','Terapia online']].map(([quote,initials,type]) => <blockquote key={initials} className="rounded-[2rem] bg-white/70 p-7"><MessageCircleHeart className="text-sage"/><p className="mt-5 font-serif text-xl leading-relaxed">{quote}</p><footer className="mt-6 text-xs uppercase tracking-[.12em] text-muted">{initials} · {type}</footer></blockquote>)}</div></div></div></section>

    <section id="contacto" className="scroll-mt-20 bg-ivory py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.72fr_1.28fr] lg:px-8"><div><p className="eyebrow">Primera sesión</p><h2 className="section-title mt-4">Dar el primer paso también es parte del proceso</h2><p className="mt-6 leading-7 text-muted">Cuéntame brevemente qué necesitas. Revisaré tu solicitud personalmente y te contactaré para confirmar la disponibilidad.</p><div className="mt-8 space-y-4"><p className="flex gap-3 text-sm"><ShieldCheck className="shrink-0 text-sage" size={20}/> Tu información se trata de forma confidencial.</p><p className="flex gap-3 text-sm"><Mail className="shrink-0 text-sage" size={20}/> Recibirás respuesta en un plazo de 24 horas.</p></div></div>
      <div className="rounded-[2rem] border border-charcoal/8 bg-white p-6 shadow-[0_30px_80px_rgba(45,45,45,.07)] sm:p-10">{status === 'success' ? <div className="grid min-h-[420px] place-items-center text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-sage text-white"><Check size={30}/></span><h3 className="mt-6 font-serif text-3xl">Cita solicitada</h3><p className="mx-auto mt-3 max-w-md text-muted">Recibirás una confirmación por email. La Dra. Torres te contactará en un plazo de 24 horas.</p></div></div> : <form onSubmit={handleSubmit} className="grid gap-5 sm:grid-cols-2">
        <Field label="Nombre completo" required><input required value={form.nombre} onChange={e=>update('nombre',e.target.value)} className="field" placeholder="Tu nombre"/></Field><Field label="Correo electrónico" required><input required type="email" value={form.email} onChange={e=>update('email',e.target.value)} className="field" placeholder="nombre@correo.com"/></Field>
        <Field label="Teléfono o WhatsApp"><input type="tel" value={form.telefono} onChange={e=>update('telefono',e.target.value)} className="field" placeholder="Número a 10 dígitos"/></Field><Field label="Tipo de terapia" required><Select value={form.terapia} onChange={v=>update('terapia',v)} options={['Individual','Pareja','Familiar','Online']} placeholder="Selecciona una opción"/></Field>
        <Field label="Modalidad" required><Select value={form.modalidad} onChange={v=>update('modalidad',v)} options={['Presencial','Online']} placeholder="Selecciona modalidad"/></Field><Field label="Horario preferido" required><Select value={form.horario} onChange={v=>update('horario',v)} options={['Mañana','Tarde','Noche']} placeholder="Selecciona horario"/></Field>
        <Field label="Fecha preferida" required><input required type="date" min={new Date().toISOString().split('T')[0]} value={form.fecha} onChange={e=>update('fecha',e.target.value)} className="field"/></Field><Field label="Hora preferida" required><Select value={form.hora} onChange={v=>update('hora',v)} options={['09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00']} placeholder="Selecciona hora"/></Field>
        <div className="sm:col-span-2"><Field label="Motivo de consulta"><textarea value={form.motivo} onChange={e=>update('motivo',e.target.value)} className="field min-h-28 resize-none" placeholder="Comparte solo lo que te haga sentir cómoda o cómodo"/></Field></div>
        <fieldset className="sm:col-span-2"><legend className="mb-3 text-sm font-semibold">¿Es tu primera vez en terapia?</legend><div className="flex gap-6">{['Sí','No'].map(option => <label key={option} className="flex cursor-pointer items-center gap-2 text-sm"><input required type="radio" name="primeraVez" value={option} checked={form.primeraVez===option} onChange={e=>update('primeraVez',e.target.value)} className="accent-clay"/>{option}</label>)}</div></fieldset>
        {status === 'error' && <p role="alert" className="sm:col-span-2 rounded-xl bg-red-50 p-4 text-sm text-red-700">No pudimos enviar tu solicitud. Revisa tu conexión e inténtalo de nuevo.</p>}<button disabled={status==='loading'} className="sm:col-span-2 flex items-center justify-center gap-2 rounded-full bg-clay px-6 py-4 font-semibold text-white transition hover:bg-clay-dark disabled:cursor-wait disabled:opacity-60" type="submit">{status==='loading' ? 'Enviando…':'Solicitar primera sesión'}{status!=='loading' && <ArrowRight size={18}/>}</button><p className="sm:col-span-2 text-center text-xs leading-5 text-muted">Este formulario no es un servicio de emergencia. Si estás en riesgo, llama a Línea de la Vida al 800 911 2000.</p>
      </form>}</div>
    </div></section>

    <footer className="bg-charcoal text-white"><div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="grid gap-10 border-b border-white/10 pb-12 md:grid-cols-3"><div><a href="#inicio" className="flex items-center gap-3 font-serif text-2xl"><span className="grid size-10 place-items-center rounded-full bg-sage"><Leaf size={18}/></span>Mente Plena</a><p className="mt-5 max-w-xs text-sm leading-6 text-white/55">Psicología clínica para acompañarte con calidez, claridad y confidencialidad.</p></div><div><p className="text-sm font-semibold">Explora</p><div className="mt-5 grid grid-cols-2 gap-3">{navLinks.map(([label,href]) => <a className="text-sm text-white/55 hover:text-white" key={href} href={href}>{label}</a>)}</div></div><div><p className="text-sm font-semibold">Atención</p><p className="mt-5 text-sm text-white/55">Ciudad de México y sesiones online</p><p className="mt-3 text-sm text-white/55">Urgencias: Línea de la Vida <a className="text-white underline" href="tel:8009112000">800 911 2000</a></p></div></div><div className="flex flex-col gap-3 pt-7 text-xs text-white/40 sm:flex-row sm:justify-between"><p>© {new Date().getFullYear()} Mente Plena</p><p>La terapia no sustituye servicios de emergencia.</p></div></div></footer>
  </main>
}

function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}{required && <span className="text-clay"> *</span>}</span>{children}</label> }
function Select({value,onChange,options,placeholder}:{value:string;onChange:(value:string)=>void;options:string[];placeholder:string}) { return <select required value={value} onChange={e=>onChange(e.target.value)} className="field"><option value="" disabled>{placeholder}</option>{options.map(option=><option key={option}>{option}</option>)}</select> }
